public class Customr {
    
    /*public static final integer gg = 11;
    public static final integer f;
    
    static
    {
        f = 22;
    }
    
    
	public static integer test()
    {
        
        system.debug('2.2');
        return 10;
    }
    
     integer test2()
    {
        return 100;
    }
    
    public void send(integer i)
    {
        
    }
    
    public integer send(integer i, integer j)
    {
        return 20;
    }


public void func()
{
    system.debug('1.1');
}    
    */
    
    
    
    
    
    
    
    
}